### PR TITLE
Large System Information -- Viral Envelopes

### PR DESCRIPTION
**Pull request by tylerjereddy**
Related to large systems #20. 

I've added a short paragraph and some citations concerning viral envelope work that leveraged MDAnalysis. I've added some images you are free to use from the virus + membrane system (which has mostly been abandoned for technical reasons, but those technical issues were revealed using MDAnalysis). You'll probably shorten this down even more, but I'm just trying to provide something you can work with and squeeze this in early this morning before another full day PyCon. 

I snuck in a few modifications to `.gitignore` too because vim swap files kept showing up.

Again, the formatting / compilation may not work perfectly, but hopefully the content can be somewhat useful.

### CODE REVIEW

**Comment by kain88-de** [comment]
Could you also give a short caption to each figure? Citing the paper it belongs to and a quick explanation of what is shown.

**Comment by orbeckst** [comment]
Short caption please, then I can easily work this in. I will probably cut out some representative graphs and make a panel that combines visualization with data. But I need to know what I am looking at.

The pictures are great! – Are they unpublished, i.e., can we include them without restrictions?

**Comment by orbeckst** [comment]
rebased against 2016, squashed gitignore commits, and started integrating

@tylerjereddy please review if you find the time

**Comment by orbeckst** [comment]
@tylerjereddy what is the black bar in the image?

**Comment by tylerjereddy** [comment]
The images and plots are unpublished and may be used freely (that is a dead end result because of semi-isotropic and isotropic systems being combined). The black line is simply a horizontal guide line to direct the reader to the rising level of the membrane.

I would indeed suggest cropping out some of the plots in the panel (I usually remove the entire top row).

brief caption for `assess_bulge.png`: Start (left) and 40 ns (right) snapshots of a CG model of the influenza A virion membrane close to a model of the human plasma membrane. A horizontal black guide line is used to emphasize the rising plasma membrane position.

brief caption for `Z_tracking_flu_membrane_system.png`: (Top) Minimum, maximum and average Z (vertical) coordinate values for system components (influenza A virus envelope, plasma membrane, and solvent) are tracked over the course of the simulation. (Bottom) Zoom-in views of the maximal Z coordinate only tracked for the same system components, to facilitate confirmation of 'membrane rising' behaviour.

**Pull request merged**
