### PR TITLE
complete example for RMSF

### PR DESCRIPTION
**Pull request by orbeckst**
- shows how to do everything that was explained in Basics
  (integration of what we just learned)
- shows how MDAnalysis and NumPy work hand in hand

### CODE REVIEW

**Comment by orbeckst** [comment]
@richardjgowers and @kain88-de , see if that fits after the basics.

**Comment by kain88-de** [comment]
Looks and reads nice. Much better then my example in #27

**Comment by kain88-de** [comment]
can we please update the pdf only in the master branch. It will avoid weird binary merge conflicts.

**Comment by orbeckst** [comment]
Ok, will leave PDF out in the future. 

(I just delete the PDF whenever there's a merge conflict and then rebuild during conflict resolution using the merged text. But I am sure it makes GitHub's merge PR unhappy.)

**Comment by kain88-de** [comment]
the basic usage already hints at it but doesn't mentiong that it's super awesome that we actually do that.

**Comment by kain88-de** [comment]
There is a typo in your code example. The first `np.zeros` the `s` is missing

**Comment by kain88-de** [comment]
Also the ylabel is wrong. it says RMSD and not RMSF

**Comment by kain88-de** [comment]
https://gist.github.com/kain88-de/edc3e17e9ee8d8dc6c3a1d8c8af9fa34

I updated the gist. I think you can just use my screenshot from #27 and add an example section for nglview with the same sentence. Then we simply close #27 that should be the easiest.

**Comment by orbeckst** [comment]
> There is a typo in your code example. The first np.zeros the s is missing
> 
> Also the ylabel is wrong. it says RMSD and not RMSF

Many thanks. Pushed a fix.

**Pull request merged**
