### PR TITLE
Add information about development community

### PR DESCRIPTION
**Pull request by kain88-de**
it adds a short sentence and adds links to the PyPi and conda
repositories.

### CODE REVIEW

**Comment by richardjgowers** [comment]
http://www.mdanalysis.org/2015/12/15/The_benefit_of_social_coding/

@orbeckst wrote this about github etc, it'd be good to include how the platform/openness has fuelled the development.  As opposed to doing everything behind closed doors

**Comment by kain88-de** [comment]
was it more behind closed doors with google code?

**Comment by orbeckst** [comment]
I want to include this in the talk. We an briefly allude to it in the paper (when mentioning approximate numbers of users, developers etc). 

Google Code was not behind closed doors at all. The issue tracker was more powerful on GC. But the little things on GitHub, the good integration (both of users and of services), @-mentions, and the smother UI (not to speak of a certain "GitHub is where the cool kids play" factor) all contributed (I think).

**Comment by orbeckst** [comment]
Not quite following #10 but I'll merge and then we can sort out the dead later....

**Pull request merged**
