### PR TITLE
interactive use/nglview.

### LINKED ISSUE #18: example for jupyter + nglview (+ pandas?)
@dotsdl (or someone else) can you provide a representative snapshot of a Jupyter notebook session that shows how one can "typically" work with MDAnalysis interactively? It would be nice to have something like 
- load trajectory
- visualize with nglview
- compute something (maybe using pandas)
- plot with matplotlib (or pandas/seaborn)

I'd like to have
- [ ] image of the notebook in the browser
- [ ] python code that could be shown in the paper

### PR DESCRIPTION
**Pull request by dotsdl**
Fixes #18.

Needs more fleshing out yet, I think. Would be nice to include a code
example for calculating something simple from a test system, or maybe
just gathering some distances between atoms of interest in a DataFrame
and getting something interesting out with groupbys? Also a plot would
be good.

Any suggestions?

### CODE REVIEW

**Comment by orbeckst** [comment]
How about some distances in AdK over a DIMS trajectory?

O. Beckstein, E. J. Denning, J. R. Perilla, and T. B. Woolf. Zipping and unzipping of adenylate kinase: Atomistic insights into the ensemble of open ↔ closed transitions. J. Mol. Biol., 394(1):160–176, 2009. doi: [10.1016/j.jmb.2009.09.009](http://doi.org/10.1016/j.jmb.2009.09.009).

For the trajectory

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD
u = mda.Universe(PSF, DCD)
```

## FRET distances

Fig 5B in the article above
- I52 - K145
- A127 - A194
- A55 - V169

adk_fret_distances

## Salt bridge zipper

Distances in Fig 7 
1-s2 0-s0022283609011164-gr7

**Comment by orbeckst** [comment]
@sseyler do you have the selections for the salt bridge zipper handy?

**Comment by kain88-de** [comment]
@orbeckst are the 98 frames we have in the test files near enough points to get such a 'nicely' converged probability anyway?

**Comment by orbeckst** [comment]
Probably not but you should still be able to see obvious changes during the course of th trajectory. 

## 

Oliver Beckstein
email: orbeckst@gmail.com

Am May 30, 2016 um 2:52 schrieb kain88-de notifications@github.com:

**Comment by kain88-de** [comment]
https://gist.github.com/kain88-de/edc3e17e9ee8d8dc6c3a1d8c8af9fa34

A gist calculating the change of distance over time for all residue pairs marked in the picture.
The plot setting I'm using aren't very good for a publication the tick labels are too small. I don't have a style file that would fit for a publication though. But if you already have one or experience about the sizes this is changed quickly.

**Comment by dotsdl** [comment]
@kain88-de I'm focusing entirely on [datreant](https://github.com/datreant/scipy_proceedings) today, so I leave this for anyone else who's interested to complete.

As for plots, you can take some of my suggestions from [this notebook](https://github.com/Becksteinlab/making-prettier-plots/blob/master/Making%20better%20plots.ipynb) if you like. There are bits on how to adjust sizes of tick labels, adding minor ticks, etc. there.

**Comment by kain88-de** [comment]
Oh I know how to do all of that. I just don't know good settings for a two column paper so that it's readable.

**Comment by dotsdl** [comment]
Plot should be 4 inches wide, and however tall it needs to be to express its content. For a timeseries, probably try 3 inches tall first (better to go wider than tall).

**Comment by dotsdl** [comment]
The paper size will likely be 8.5 x 11 inches. @orbeckst is this correct?

**Comment by richardjgowers** [comment]
Seaborn might even have a publication preset?

**Comment by kain88-de** [comment]
yeah I know they are soo much worse. I don't know what they thought with the tiny fonts they use

**Comment by kain88-de** [comment]
actually doesn't look that bad when included.

**Comment by orbeckst** [comment]
I just pushed PR #30 and the example uses the RMSF calculation for AdK. 

@kain88-de it would be nice if the nglview window could also show AdK.

**Comment by orbeckst** [comment]
> The paper size will likely be 8.5 x 11 inches. @orbeckst is this correct?

Probably, it's US and I think that's what comes out when I build the paper.

**Comment by kain88-de** [comment]
I extended the stub from David minimally and added a figure/code how to calculate the distance for opening. The code example is minimal but I link to the gist that I have created.

**Comment by orbeckst** [comment]
@kain88-de the distance calculations look good to me. 
But if you think that #30 is enough then just make a notebook session with AdK and we just show the nglviewer window with adk.

You could add the RMSF example into the notebook, see https://gist.github.com/orbeckst/94b2aa910eb9dbfddbe9ef6dacc4e384  

Don't worry about actually reproducing the graph. I have to check what equilibrium trajectory I used for the example... perhaps it was the test XTC and TPR (although then one should rmsfit before).

**Comment by orbeckst** [comment]
FYI: I found the trajectories and the whole example. It was something that I considered using for the CECAM workshop. Everything is in [MDAnalysis_examples.ipynb](https://github.com/Becksteinlab/MDAnalysis-workshop/blob/master/notebooks/MDAnalysis_examples.ipynb) and the trajectories are in a dropbox folder [CECAM-Workshop/MDAnalysis/Optional](https://www.dropbox.com/sh/ln0klc9j7mhvxkg/AAAdVJ-pj1pi23FgInsig3D7a/Optional?dl=0).

**Comment by orbeckst** [comment]
@kain88-de I'll do as you said in https://github.com/MDAnalysis/scipy_proceedings/pull/30#issuecomment-222545869

**Comment by orbeckst** [comment]
rebased and condensed (see commit message)

**Comment by orbeckst** [comment]
I'll merge this but will keep the branch around for the additional work and figures (so that we can go back to it).

**Pull request merged**
