### PR TITLE
Max changes

### PR DESCRIPTION
**Pull request by kain88-de**
Some small changes. I tried to keep every commit self contained. This should make it easy to delete changes that other don't agree on before it is merged.

The commit message contain a brief explanation for all changes

### CODE REVIEW

**Comment by richardjgowers** [comment]
I'd rather use line breaks for a reason rather than just 80? chars.  I try and have each point in a sentence be a line (#9) which makes editing it easier.

**Comment by kain88-de** [comment]
We can also have a line for each paragraph.

I'm using emacs and vim only. Specifically vim movement commands work best with hard line breaks. Both understand the concept of a paragraph as text that isn't separated by a newline.  So I tend to favor text with hard line breaks. I'm also OK with having one line per paragraph.

**Comment by dotsdl** [comment]
Can we do one line per sentence/independent clause? That makes diffs more meaningful, and gets those of us that use a text editor that relies on hard breaks for basic navigation (e.g. vim) what we need to function. :D

**Comment by orbeckst** [comment]
@kain88-de can we try @dotsdl 's suggestion #10 to use one line break per sentence? In my experience, hard line breaks after 79 col lead to fairly messy diffs (even though I still use it myself... mainly because I did not know about `visual-line-mode` in emacs...). #10 might be a decent compromise.

**Comment by orbeckst** [comment]
@kain88-de are you simply redoing the PR? (I was happy with the content.)

**Comment by kain88-de** [comment]
Yep I'm on the train home updates are coming later in the evening.

**Pull request closed without merging**
